djangoSimpleNotepad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from appnotes.views import (note_list_view, finish_item, delete_item, recover_item)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', note_list_view, name='note-list'),
    path('finish-item/<id>/', finish_item, name='finish-note-item'),
    path('delete-item/<id>/', delete_item, name='delete-note-item'),
    path('recover-item/<id>/', recover_item, name='recover-note-item'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

appnotes/models.py
from django.db import models
from django.shortcuts import redirect, reverse

NOTE_LABELE_CHOICES = (
    ('P', 'primary'),
    ('SE', 'secondary'),
    ('SU', 'success'),
    ('D', 'danger'),
    ('W', 'warning'),
    ('I', 'info'),
    ('L', 'light'),
    ('D', 'dark'),
)

class Note(models.Model):
    title = models.CharField(max_length=128)
    due_date = models.DateTimeField()
    note_label = models.CharField(choices=NOTE_LABELE_CHOICES, max_length=2)
    finished = models.BooleanField(default=False)


    def __str__(self):
        return self.title

    def get_finish_item_url(self):
        return reverse('finish-note-item', kwargs={
            'id': self.id
        })

    def get_recover_item_url(self):
        return reverse('recover-note-item', kwargs={
                'id': self.id
            })

    def get_delete_item_url(self):
        return reverse('delete-note-item', kwargs={
                'id': self.id
            })

appnotes/forms.py
from django import forms

from .models import Note

class NoteModelForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'due_date', 'note_label')

appnotes/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Note
from .forms import NoteModelForm

def note_list_view(request):
    form = NoteModelForm()
    if request.method == 'POST':
        form = NoteModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('note-list')
    active_notes = Note.objects.filter(finished=False)
    finished_notes = Note.objects.filter(finished=True)
    context_page = {
        'notes': active_notes,
        'finished_list': finished_notes,
        'form': form
    }
    return render(request, 'note_list.html', context_page)

def finish_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.finished = True
    note.save()
    return redirect('note-list')

def recover_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.finished = False
    note.save()
    return redirect('note-list')

def delete_item(request, id):
    note = get_object_or_404(Note, id=id)
    note.delete()
    return redirect('note-list')

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">

    <meta name="generator" content="Hugo 0.84.0">
    <title></title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">




  </head>
  <body>
  <script src="https://kit.fontawesome.com/daeb52917d.js" crossorigin="anonymous"></script>
  <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Ninth navbar example">
    <div class="container-xl">
      <a class="navbar-brand" href="#">Container XL</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07XL" aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample07XL">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown07XL" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown07XL">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <form>
          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>
  </header>

<div class="col-lg-8 mx-auto p-3 py-md-5">


  <main>
      {% block content %}

      {% endblock content %}

  </main>
  <footer class="pt-5 my-5 text-muted border-top">

  </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>


  </body>
</html>

templates/note_list.html
{% extends 'base.html' %}

{% block content %}


    <div class="text-center">
        <h2>There are our notes.
            <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button"
               aria-expanded="false" aria-controls="collapseExample"><i class="fa-regular fa-circle-plus"></i></a>
        </h2>
    </div>

    <hr>


    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <form method="POST">
                <div class="mb-3">
                    <label class="form-label" for="id_title">Note title</label>
                    {{ form.title }}

                </div>
                <div class="mb-3">
                    <label class="form-label" for="id_due_date">Due date</label>
                    {{ form.due_date }}
                </div>
                <div class="mb-3 form-check">
                    {{ form.note_label }}
                    <label class="form-check-label" for="id_note_label">Label</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>


    <hr>



    <div class="row">
        {% for note in notes %}
            <div class="col-12">
                {% include 'note_snippet.html' with note=note type='DELETE' %}
            </div>


        {% endfor %}
    </div>

    <div class="text-center">
        <h2>There are our fineshed notes.</h2>
    </div>
    <hr>

    <div class="row">
        {% for note in finished_list %}
            <div class="col-12">
                {% include 'note_snippet.html' with note=note type='ADD' %}
            </div>


        {% endfor %}
    </div>

{% endblock content %}

templates/note_snippet.html
<style>
        h3 {
            position: relative;
        }

        .icons {
            position: absolute;
            right: 5px;

        }
    </style>

<div class="card">
    <div class="card-body">
        <h3>{{ note.title }}
            <span class="badge bg-{{ note.get_note_label_display }}">
                                {{ note.due_date }}
            </span>
            <span class="icons">
                {% if type == 'DELETE' %}
                        <a href="{{ note.get_finish_item_url }}"><i class="fa-regular fa-circle-check"></i></a>
                {% else %}
                        <a href="{{ note.get_recover_item_url }}"><i class="fa-regular fa-circle-xmark"></i></a>
                {% endif %}
                        <a href="{{ note.get_delete_item_url }}"><i class="fa-solid fa-trash-arrow-up" style="color: red"></i></a>
            </span>
        </h3>


    </div>
</div>